name: hasmak_ecommerce
description: A new mobil Flutter application for Hasmak e-commerce.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/c1.jpg
    - images/c2.jpg
    - images/c3.jpg
    - images/c4.jpg
    - images/c5.jpg
    - images/c6.jpg
    - images/c7.jpg
    - images/c8.jpg
    - images/c9.jpg
    - images/c10.jpg
    - images/c11.jpg
    - images/c12.jpg
    - images/c13.jpg
    -
    - images/logo2.png
    - images/beyazlogo.png
    - images/logobeyaz2.png
    - images/logof.jpg
    - images/m1.jpeg
    - images/w1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg
    - images/m2.jpg
    - images/f.png
    - images/f2.png
    - images/f3.png
    - images/f4.png
    - images/f5.png
    - images/wood.jpg
    - images/logomini.png
    - images/topselling.png
    - images/sidebarback.png
    - images/sidebar400.png
    - images/side900.png
    - images/deneme.png
    - images/deneme2.png
    - images/cats/tshirt.png
    - images/cats/cat1.png
    - images/cats/cat2.png
    - images/cats/cat3.png
    - images/cats/cat4.png
    - images/cats/cat5.png
    - images/cats/cat6.png
    - images/cats/shoe.png
    - images/cats/dress.png
    - images/cats/accessories.png
    - images/cats/formal.png
    - images/cats/informal.png
    - images/cats/tshirt.png
    - images/cats/jeans.png
    - images/products/blazer1.jpeg
    - images/products/blazer2.jpeg
    - images/products/dress1.jpeg
    - images/products/logo.jpg
    - images/products/logo2.png
    - images/products/deneme.jpg
    - images/products/logobeyaz.jpg
    - images/products/logo22.png
    - images/products/logoyazi.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
